---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - recipe[site-forgetypo3org::default]
    attributes:
      dev_mode: true
      redmine:
        hostname: forge.vagrant
        thin_servers: 1
      mysql:
        server_root_password: root
    driver_config:
      network:
      - ["private_network", {ip: "192.168.88.89"}]
