---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[site-forgetypo3org::default]
    attributes:
      dev_mode: true
      site-forgetypo3org:
        ssl_certificate: wildcard.vagrant
        amqp:
          server: mq.vagrant
          user: forge
      site-gittypo3org:
        amqp:
          server: mq.vagrant
          user: forge
      gitweb:
        ssl_certificate: wildcard.vagrant
    driver_config:
      network:
      - ["private_network", {ip: "192.168.88.89"}]
