rvm:
  - 1.9.3
  - 2.0.0
env: USE_SYSTEM_GECODE=1
before_install:
    - sudo apt-get install -qq libgecode-dev
before_script:
  - bundle exec berks install
script:
  - bundle exec foodcritic -f any .
